modLoader="javafml" #mandatory
loaderVersion="[46,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU Lesser General Public License v3"
issueTrackerURL="https://github.com/cationick/DomesticationInnovation/issues" #optional
[[mods]] #mandatory
modId="domesticationinnovation" #mandatory
version="1.7.1" #mandatory
displayName="Domestication Innovation (Fixed)" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/domestication-innovation-fixed" #optional
authors="Alexthe668, FallenReaper, Yosh, cationick" #optional
description='''Fork of original DI mod, fixing crashes. Vastly improves upon and compliments tameable mobs, both from vanilla and other mods.'''
logoFile="domesticationinnovation.png" #optional
[modproperties.domesticationinnovation]
    catalogueItemIcon="domesticationinnovation:collar_tag"
[[dependencies.domesticationinnovation]] #optional
    # the modid of the dependency
    modId="citadel" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[2.4.0,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="AFTER"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
[[dependencies.domesticationinnovation]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
